### ISSUE TITLE
Fails to pull the correct tag with submodules

### ISSUE THREAD

**Issue by quanah** [chrismaes87/git-archive-with-submodules#1]
I have a git repository with multiple submodules.  Periodically we cut releases and apply the same tag name to the parent and all of its submodules.

If I use this utility to extract the source, the submodules are pulled in at HEAD state and not at the state they were in at the time of the tag that was passed in to be used for generating the tarball.

**Comment by quanah** [comment]
Same problem occurs if I use the commit hash of the parent git repo for when the tag was made.

**Comment by chrismaes87** [comment]
I have created version 1.1.0 that should fix your problem. no need for extra parameters, when you reference a certain commit on your super-repo, the script should automatically take the correct hashes for all the submodules.

**Comment by quanah** [comment]
Great thanks I'll give it a try :)
